Fix Errno::EACCES when removing git dir
First I added a failing test:

```
SystemsCliTest#test_git:
RuntimeError: Command: /Users/rschneeman/Documents/projects/rundoc/bin/rundoc /var/folders/yr/yytf3z3n3q336f1tj2b2j0gw0000gn/T/d20240715-22479-imrfiv/rundoc.md failed: ## Running your docs
## No .env file found /var/folders/yr/yytf3z3n3q336f1tj2b2j0gw0000gn/T/d20240715-22479-imrfiv/.env, skipping dotenv loading
## Working dir is /var/folders/yr/yytf3z3n3q336f1tj2b2j0gw0000gn/T/d20240715-22483-3l6enl
Running: $ '(echo "hello world" >> lol.txt) 2>&1'
Running: $ '(git init .) 2>&1'
    Initialized empty Git repository in /private/var/folders/yr/yytf3z3n3q336f1tj2b2j0gw0000gn/T/d20240715-22483-3l6enl/.git/
Running: $ '(git add .) 2>&1'
Running: $ '(git commit -m first) 2>&1'
    [main (root-commit) bde4306] first
     1 file changed, 1 insertion(+)
     create mode 100644 lol.txt
Running: $ '(echo "so long and thanks for all the fish" >> lol.txt) 2>&1'
Running: $ '(git add . && git commit -m second) 2>&1'
    [main 831f6dd] second
     1 file changed, 1 insertion(+)
## Success! sanitizing output
## Writing RUNdoc output to /var/folders/yr/yytf3z3n3q336f1tj2b2j0gw0000gn/T/d20240715-22483-3l6enl/README.md
## Running after build scripts
## Saving to /var/folders/yr/yytf3z3n3q336f1tj2b2j0gw0000gn/T/d20240715-22479-imrfiv/rundoc_output
## Cleaning on success directory, /var/folders/yr/yytf3z3n3q336f1tj2b2j0gw0000gn/T/d20240715-22479-imrfiv/rundoc_output
## Cleaning working directory /var/folders/yr/yytf3z3n3q336f1tj2b2j0gw0000gn/T/d20240715-22483-3l6enl
## Cleaning tmp working directory, /var/folders/yr/yytf3z3n3q336f1tj2b2j0gw0000gn/T/d20240715-22483-3l6enl
/Users/rschneeman/.rubies/ruby-3.3.1/lib/ruby/3.3.0/fileutils.rb:2279:in `initialize': Permission denied @ rb_sysopen - /var/folders/yr/yytf3z3n3q336f1tj2b2j0gw0000gn/T/d20240715-22479-imrfiv/rundoc_output/./.git/objects/3b/18e512dba79e4c8300dd08aeb37f8e728b8dad (Errno::EACCES)
```

Then I fixed it, by: Moving the directory instead of copying it before deleting the working tmpdir. I don't know why this works, but it does.