Fix missing require
```
$ be rake test
rake aborted!
LoadError: cannot load such file -- cgi/cookie (LoadError)
/Users/rschneeman/Documents/projects/rundoc/lib/rundoc/code_command/website/driver.rb:3:in '<top (required)>'
/Users/rschneeman/Documents/projects/rundoc/lib/rundoc/code_command/website.rb:6:in '<top (required)>'
/Users/rschneeman/Documents/projects/rundoc/lib/rundoc/code_command.rb:17:in '<top (required)>'
/Users/rschneeman/Documents/projects/rundoc/lib/rundoc.rb:127:in '<top (required)>'
```